analytics: # система записи аналитики использования подов. Пока что эксперементальная версия
  enabled: false

git:
  webhook-url-token: "2"

api:
  enabled: true # разрешить использование апи для клиента cubectl
  token: "7F86E518A587B53AA930303CF61751C2A9D719F0B044A68ED93181546636DD4BB3BA0DE6251BFAE9BFF17D5D0240D8FED60B286A7D2718B3232114338920B8B6" # токен клиента. Используйте длинные сложные строки. Это будет использоваться для хэширования запросов от клиента.